server:
  port: 8803
 
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置需要绑定的rabbitMQ的信息
        defaultRabbit: # 消息服务设置的名称，用于bindings整合
          type: rabbit # 消息组件类型
          environment: # rabbitmq环境配置
            spring: 
              rabbitmq:
                host: 192.168.0.106
                port: 5672
                username: admin
                password: admin
      bindings: # 服务的整合处理
        input: # 通道名
          destination: test-stream # rabbitmq的exchange的名称
          content-type: application/json
          binder: defaultRabbit # 消息服务设置的名称
          group: A
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka