server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
    sentinel:
      transport:
        client-ip: 192.168.0.104
        dashboard: 192.168.0.106:8080
        port: 8719
service-url:
  nacos-user-service: http://nacos-payment-provider