server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
  datasource:
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.106:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zsl
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
      
ribbon:
  # 建立连接后从服务器获取可用资源的时间
  ReadTimeout: 10000
  ConnectTimeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhusl.springcloud.domain
